"""Initial migration.

Revision ID: 88637e237cf6
Revises: 
Create Date: 2024-08-22 11:41:40.366363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88637e237cf6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interaction_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_behavior',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type_id', sa.Integer(), nullable=False),
    sa.Column('qa_score', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['interaction_type_id'], ['interaction_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_behavior')
    op.drop_table('interaction_type')
    op.drop_table('agent')
    # ### end Alembic commands ###
